platform :ios, "13.2"
use_modular_headers!

target "GameOfRunes" do
  pod "SwiftLint"
  pod "SnapKit"
  pod "RealmSwift"
  
  target "GameOfRunesTests" do
    inherit! :search_paths
    pod "Cuckoo"
  end
end
