platform :ios, "13.2"

target "GameOfRunes" do
  pod "SwiftLint"
  pod "SnapKit"
  pod "Firebase/Database"
  pod "RealmSwift", :modular_headers => true
  pod "Realm", :modular_headers => true
  pod "ReachabilitySwift"

  target "GameOfRunesTests" do
    inherit! :search_paths
    pod "Cuckoo"
  end
end
